import SearchInput from "@/components/inventory/SearchInput";
import Navbar from "@/components/layout/Navbar";
import PageTitle from "@/components/layout/PageTitlte";
import UserMenu from "@/components/layout/UserMenu";
import { ProductProvider } from "@/contexts/products.context";
import { StorageProvider } from "@/contexts/storage.context";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import IndexPageContainer from "./page.container";
import AddProductBtn from "@/components/inventory/AddProductBtn";
import FilterBySupplier from "@/components/inventory/FilterBySupplier";
import ScanButton from "@/components/utils/scan-button";
import { SupplierProvider } from "../../contexts/suppliers.context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Top Values Brand",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <main className="flex w-full">
        <IndexPageContainer>
          <Navbar />
          <div className="main_layout flex justify-end ">
            <ProductProvider>
              <StorageProvider>
                <SupplierProvider>
                  <div className="table_header py-10 px-[46px] flex justify-between items-center fixed top-0 z-40 bg-white text-black dark:bg-dark transition-colors duration-[0.6s] ease-in-out h-[115px]">
                    <PageTitle />
                    <div className="flex items-center gap-4">
                      <AddProductBtn />
                      <SearchInput />
                      <FilterBySupplier />
                      <UserMenu />
                    </div>
                  </div>
                  {children}
                  <ScanButton />
                </SupplierProvider>
              </StorageProvider>
            </ProductProvider>
          </div>
        </IndexPageContainer>
      </main>
    </>
  );
}
