import type { Metadata } from "next";
import { TrackedProductsProvider } from "../../../contexts/trackedProducts.context";
import IndexPageContainer from "../page.container";
import { OrdersProvider } from "@/contexts/orders.context";
import { POGeneratorNavbar } from "../pogenerator/components/POGeneratorNavbar";

export const metadata: Metadata = {
  title: "Warehouse - TVB",
  description: "Generated by create next app",
};

export default function POGeneratorLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navLinks = [
    {
      name: "Incoming POs",
      href: "/warehouse/incoming-shipments",
    },
    {
      name: "Outgoing Shipments",
      href: "/warehouse/outgoing-shipments",
    },
  ];

  return (
    <>
      <IndexPageContainer>
        <OrdersProvider>
          <main className="flex w-full h-fit flex-col items-center mt-[56px] relative">
            <TrackedProductsProvider>
              <POGeneratorNavbar navLinks={navLinks} />
              {children}
            </TrackedProductsProvider>
          </main>
        </OrdersProvider>
      </IndexPageContainer>
    </>
  );
}
